[FIX] stock_storage_type: AttributeError: estimated_pack_weight_kg
Fixes `AttributeError: 'stock.quant.package' object has no attribute 'estimated_pack_weight_kg'`.
That field was removed in https://github.com/OCA/stock-logistics-tracking/commit/d3d646d1fa529e10a333bbb0b3f2412a3f709344
(cf. related PR: https://github.com/OCA/stock-logistics-tracking/pull/48)